### ISSUE TITLE
Change registered name

### ISSUE THREAD

**Issue by ng-hai** [shoutem/cli#1]
My account had been registered with a whitespace that cause I cannot install new app because of `Name contains illegal characters`. How can I change it ?
![image](https://cloud.githubusercontent.com/assets/19520278/23224090/8b353a0a-f95f-11e6-9276-70a895709957.png)

**Comment by tenodi** [comment]
Hi @ng-hai. We've fixed this in the meantime and we're not allowing the developers to register with illegal characters. We also renamed you to `nghai` developer. Do `shoutem logout` and `shoutem login`. That should do the work :)
