### ISSUE TITLE
sudo npm install -g @shoutem/cli - FAIL

### ISSUE THREAD

**Issue by anthfran** [shoutem/cli#14]
Any ideas on how to fix this?

I think it's actually an issue with ngrok since "sudo npm install -g ngrok" fails as well.

I'm on OSX 10.12.5

MacBook-Pro-4:~ anthony$ sudo npm install -g @shoutem/cli
npm WARN deprecated babel-preset-node7@1.5.0: Use https://github.com/babel/babel-preset-env instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/shoutem -> /usr/local/lib/node_modules/@shoutem/cli/src/shoutem.js

> @shoutem/cli@0.8.152 postinstall /usr/local/lib/node_modules/@shoutem/cli
> node src/scripts/postinstall.js

> ngrok@2.2.11 postinstall /usr/local/lib/node_modules/@shoutem/cli/node_modules/ngrok
> node ./postinstall.js

ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip ...
ngrok - error downloading binary. { Error: EACCES: permission denied, open '/usr/local/lib/node_modules/@shoutem/cli/node_modules/ngrok/bin/ngrok.zip'
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/@shoutem/cli/node_modules/ngrok/bin/ngrok.zip' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngrok@2.2.11 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngrok@2.2.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anthony/.npm/_logs/2017-06-20T13_42_52_448Z-debug.log

**Comment by anthfran** [comment]
Ughh.. worked around it. The issue is the download command (cURL I assume?) isn't being run with sudo so cannot download to the directory. I changed the global node_modules directory (command below) to be owned by the user so I no longer needed to run "npm install -g @shoutem/cli" with sudo.

$ chown -R <username> /usr/local/lib/node_modules

**Comment by Vladimir-Vdovic** [comment]
Closing this issue since it's resolved. Prompt for reopen if issue somehow becomes relevant again.
