### ISSUE TITLE
npm run configure` failed with code 1

### ISSUE THREAD

**Issue by kaman1** [shoutem/cli#15]
`npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "configure"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @shoutem/mobile-app@1.1.2 configure: `node scripts/configure`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @shoutem/mobile-app@1.1.2 configure script 'node scripts/configure'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @shoutem/mobile-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/configure
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @shoutem/mobile-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @shoutem/mobile-app
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ghostshield/.shoutem/production/client/5958/npm-debug.log`

**Comment by Vladimir-Vdovic** [comment]
We just released our new platform, as well as a new Development flow. You can find the documentation [here](http://shoutem.github.io/docs/extensions/tutorials/getting-started).

Using the new CLI as well as the new flow it supports, you should no longer receive errors with the configuration script.
