### ISSUE TITLE
Command 'shoutem configure' crash

### ISSUE THREAD

**Issue by semvankoutrik** [shoutem/cli#154]
I created and published an extension, but after this I get the following errors while trying to run 'shoutem configure':

`
(node:81125) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:81125) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:81125) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/Users/semvankoutrik/Documents/shoutem/Loyalty-App-4/scripts/classes/app-configurator.js:111:38)
    at Request.self.callback (/Users/semvankoutrik/Documents/shoutem/Loyalty-App-4/scripts/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (/Users/semvankoutrik/Documents/shoutem/Loyalty-App-4/scripts/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:527:28)
    at IncomingMessage.<anonymous> (/Users/semvankoutrik/Documents/shoutem/Loyalty-App-4/scripts/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
`npm run configure` failed with code 1
`

I am using node v16.16.0 and npm v8.11.0

**Comment by sstimac** [comment]
Resolved via slack
