### ISSUE TITLE
Validation failed on shoutem push

### ISSUE THREAD

**Issue by zenesys0069** [shoutem/cli#155]
Hi there is already a working extension, today i have made some changes but i'm unable to re-push my extension

$ shoutem push
DEPRECATED:
'shoutem push' is deprecated and will be removed with the next major version of the Shoutem CLI. Shoutem now supports release candidate versioning, which allows developers to 'shoutem publish', for example, 1.0.0-rc.0 versioned extensions which are labeled as "Beta" versions in the Shoutem Builder. App owners who update to RC versions also have the option to revert to the last "stable" (non-rc) version.
Uploading Profile:
Checking for required files...[OK]
Checking the extension code for syntax errors...npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.       
[OK]
Building the server part... [OK]
Building the app part... [OK]
Packing extension... [OK]
Validation error

Use shoutem last-error for more information.

shoutem last-error
message:    null
request: 
  method:   put
  redirect: follow
  headers: 
    _headers: 
      accept: 
        - application/vnd.api+json
      content-type:
        - multipart/form-data; boundary=--------------------------033923493994535499492828
  url:      https://extensions.api.shoutem.com/v1/extensions/akshay.profile@0.0.1
  follow:   20
  compress: true
  counter:  0
  body:
    _overheadLength:  166
    _valueLength:     0
    _valuesToMeasure:
      -
        fd:             null
        path:           C:\Users\AKSHAY~1\AppData\Local\Temp\tmp-1920HcQViGXXLF6S\extension.tgz
        flags:          r
        mode:           438
        end:            null
        bytesRead:      3114
        closed:         true
        _readableState:
          objectMode:        false
          highWaterMark:     65536
          buffer:
            head:   null
            tail:   null
            length: 0
          length:            0
          pipes:
            (empty array)
          flowing:           true
          ended:             true
          endEmitted:        true
          reading:           false
          constructed:       true
          sync:              false
          needReadable:      false
          emittedReadable:   false
          readableListening: false
          resumeScheduled:   false
          errorEmitted:      false
          emitClose:         true
          autoDestroy:       true
          destroyed:         true
          errored:           null
          closed:            true
          closeEmitted:      true
          defaultEncoding:   utf8
          awaitDrainWriters: null
          multiAwaitDrain:   false
          readingMore:       false
          dataEmitted:       true
          decoder:           null
          encoding:          null
        _events:
          data:
            - null
            - null
        _eventsCount:   2
    writable:         false
    readable:         true
    dataSize:         0
    maxDataSize:      2097152
    pauseStreams:     true
    _released:        true
    _streams:
      (empty array)
    _currentStream:   null
    _insideLoop:      false
    _pendingNext:     false
    _boundary:        --------------------------033923493994535499492828
    _events:
    _eventsCount:     0
  bodyUsed: false
  size:     0
  timeout:  0
  _raw:
    (empty array)
  _abort:   false
  protocol: https:
  hostname: extensions.api.shoutem.com
  port:     null
  path:     /v1/extensions/akshay.profile@0.0.1
  auth:     null
body:
  errors:
    -
      status: 400
      title:  validation error
      code:   em_extension_validation_extensionVersionInvalid
response:
  url:        https://extensions.api.shoutem.com/v1/extensions/akshay.profile@0.0.1
  status:     400
  statusText: Bad Request
  headers:
    _headers:
      access-control-allow-origin:
        - *
      content-type:
        - application/json; charset=utf-8
      content-length:
        - 113
      etag:
        - W/"71-WtjZ+Re4rwsjLl5oeOumslbYh1o"
      vary:
        - Accept-Encoding
      date:
        - Thu, 18 Aug 2022 07:31:55 GMT
      connection:
        - close
  ok:         false
  body:
    _readableState:
      objectMode:        false
      highWaterMark:     16384
      buffer:
        head:   null
        tail:   null
        length: 0
      length:            0
      pipes:
        (empty array)
      flowing:           true
      ended:             true
      endEmitted:        true
      reading:           false
      constructed:       true
      sync:              false
      needReadable:      false
      emittedReadable:   false
      readableListening: false
      resumeScheduled:   false
      errorEmitted:      false
      emitClose:         true
      autoDestroy:       true
      destroyed:         true
      errored:           null
      closed:            true
      closeEmitted:      true
      defaultEncoding:   utf8
      awaitDrainWriters: null
      multiAwaitDrain:   false
      readingMore:       false
      dataEmitted:       true
      decoder:           null
      encoding:          null
    _events:
    _eventsCount:   4
    _writableState:
      objectMode:         false
      highWaterMark:      16384
      finalCalled:        true
      needDrain:          false
      ending:             true
      ended:              true
      finished:           true
      destroyed:          true
      decodeStrings:      true
      defaultEncoding:    utf8
      length:             0
      writing:            false
      corked:             0
      sync:               false
      bufferProcessing:   false
      writecb:            null
      writelen:           0
      afterWriteTickInfo: null
      buffered:
        (empty array)
      bufferedIndex:      0
      allBuffers:         true
      allNoop:            true
      pendingcb:          0
      constructed:        true
      prefinished:        true
      errorEmitted:       false
      emitClose:          true
      autoDestroy:        true
      errored:            null
      closed:             true
      closeEmitted:       true
    allowHalfOpen:  true
  bodyUsed:   true
  size:       0
  timeout:    0
  _abort:     false
  _bytes:     113
statusCode: 400

Enviroment : -
Platform : Windows
shoutem cli : 0.14.4
node : v16.16.0
npm : 8.11.0

**Comment by sstimac** [comment]
Extension version invalid as described in the error code.
