### ISSUE TITLE
Shoutem clone

### ISSUE THREAD

**Issue by Lowisoft** [shoutem/cli#17]
Hi,

I have updated the cli from shoutem to the last version. Both commands Shoutem run-android or shoutem run-ios are no longer supported, From now on you have the possibility to download a copy of the code with the command "clone".

Well I have tried to use the command with a real simple App. I have created an extension with only the "Hello World" example. In the shoutem builder I have link the extension to a new app called 'Local Test".

Unfortunately the command "shoutem clone" doesn't work. The command stops coincidentally by trying to download a shoutem extension. Please look at the attached image.

![image](https://user-images.githubusercontent.com/30078772/28708375-577dc60e-737c-11e7-89e9-6fd61f0f11a9.png)

Thanks for any hint to solve the problem.

**Comment by Vladimir-Vdovic** [comment]
I can't replicate this error no matter what I try to do on Windows. Be it on an actual Windows machine or a virtual machine. It clones without issue, not failing during extension download.

Make sure your network connection isn't dropping the ball here, one user reported a similar issue, but upon connecting to a stable network connection it was resolved.

**Comment by Lowisoft** [comment]
Hi Vladimir, thanks for your fast answer.

Network connection problem was also my first thought. Therefore, I have tried it on different networks, sadly with the same result.  So I have tested to clone the app on an other computer, with success.

Seems that the problem comes from users rights I haven't to access different folder on different hard disk.
