### ISSUE TITLE
shoutem clone --noconfigure & shoutem configure

### ISSUE THREAD

**Issue by seblau** [shoutem/cli#18]
He, cloning an app with the `--noconfigure` option and afterwards running `shoutem configure` is not compatible. There are 3 additional steps required, in order to be able to run `shoutem configure` after cloning with the `--noconfigure` option.

- npm install
- cd scripts && npm install
- Create `config.json` file with correct app_id, api endpoints and auth token

 For me it would make sense, to pack those steps into either the `shoutem configure` or the `shoutem clone --noconfigure` command, in order to be able to run `shoutem clone --noconfigure` & `shoutem configure` without any intermediate steps.

Does that make sense? Or is there some other purpose behind the `--noconfigure` option?

shoutem cli version: 0.9.1

**Comment by Vladimir-Vdovic** [comment]
The purpose of the `--noconfigure` flag is to allow the developer to not have to wait for the configuration step.

We do intend for it to be configurable without the steps between, it's just a matter of time before we implement it. Thanks for the feedback and your idea on how to resolve the issue.

**Comment by Vladimir-Vdovic** [comment]
This is now available with the Shoutem CLI v0.9.6. Closing issue.
