### ISSUE TITLE
Cannot read property 'createAppAsync' of undefined

### ISSUE THREAD

**Issue by sglocastic** [shoutem/cli#2]
I am following the "Getting started" tutorial on your documentation and when I type `shoutem install` and type the name of the app i get this:

```
? You have no apps. Create a new one? yes
? App name myapp
Cannot read property 'createAppAsync' of undefined
```

**Comment by ikatun** [comment]
@sglocastic Try updating the @shoutem/cli, the issue should be fixed now :)
