### ISSUE TITLE
Error when cloning application

### ISSUE THREAD

**Issue by tiarachmad** [shoutem/cli#23]
i am cloning application using the `soutem clone` command and i got this error :
`FetchError: request to https://apps.beta.shoutem.com/v1/apps/20900/platform failed, reason: getaddrinfo EAI_AGAIN apps.beta.shoutem.com:443

{ Error: getaddrinfo EAI_AGAIN www.google-analytics.com:80
    at Object.exports._errnoException (util.js:1026:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'www.google-analytics.com',
  host: 'www.google-analytics.com',
  port: 80 }
`
please help me.

**Comment by Vladimir-Vdovic** [comment]
I had no issues cloning your app. (As an admin, I'm able to do so, other non-admin users can't)

I run 3.1.10 npm and 6.11.0 Node.js on Mac, 4.1.2 npm and 7.6.0 Node.js on my Windows machine. Could you try using those as well on whatever OS you're running to see if that resolves the issue?

`getaddrinfo EAI_AGAIN` is an error tied to connection time outs, so you may have experienced connection issues as well during the clone.

**Comment by Vladimir-Vdovic** [comment]
Closed due to inactivity. Prompt for reopen if issue is still relevant.
