### ISSUE TITLE
`npm run configure -- --production` failed with code 1

### ISSUE THREAD

**Issue by gorsim** [shoutem/cli#24]
I have built a new shoutem App (free version) and cannot configure it - I get the above message.

C:\Users\Public\FW_Installer_Tool_Brasil>shoutem configure --production

> @shoutem/platform@0.58.18 configure C:\Users\Public\FW_Installer_Tool_Brasil
> node scripts/configure "--production"

Starting build for app 22489
Cleaning temp files: 4.355ms
Configuration download failed! Error: 404 - not found Configuration id cannot be resolved
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @shoutem/platform@0.58.18 configure: `node scripts/configure "--production"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @shoutem/platform@0.58.18 configure script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Simon Gordon\AppData\Roaming\npm-cache\_logs\2017-09-17T20_56_13_403Z-debug.log
`npm run configure -- --production` failed with code 1

I attach the log file.

[2017-09-17T20_56_13_403Z-debug.txt](https://github.com/shoutem/cli/files/1309387/2017-09-17T20_56_13_403Z-debug.txt)

**Comment by Vladimir-Vdovic** [comment]
Your app needs to be published in the Builder in order to be configured for production. The `Configuration id cannot be resolved` error is referencing the production configuration, which isn't created until your app is published via the Builder.

**Comment by gorsim** [comment]
Ah OK so you only get that when you pay right?

**Comment by Vladimir-Vdovic** [comment]
That is correct.

Alternatively you can use `shoutem configure --release` and work from there. The assets are bundled and the `release` flag is raised in `config.json`.

Issue seems to be resolved, closing it.

**Comment by gorsim** [comment]
Hi Vlad - I had run `shoutem configure --release` and in the config.json file is showed the release flag as True so just to be sure are you saying that you HAVE to Publish from Shoutem and go to a paying plan to be able to work on it and publish to google play?  Not that I mind paying but I wanted to play around with free stuff to learn.

**Comment by Vladimir-Vdovic** [comment]
You don't have to, no, but you have to detach from Shoutem's Cloud Storage before publishing. In other words, you have to host your own content (e.g. News articles used in the News extension).

Additional note, you may have to set the `production` flag to `false` in `config.json` before you can successfully configure the app again.

**Comment by gorsim** [comment]
Thanks
