### ISSUE TITLE
Login with google

### ISSUE THREAD

**Issue by franciscocpg** [shoutem/cli#35]
I've sign in to https://builder.shoutem.com with my google account.

Now I'm not sure how to use `shoutem login` because I have no password.

What am I suppose to do in this case?

**Comment by Vladimir-Vdovic** [comment]
We're working on a more user friendly way to utilize social login with the CLI, but for now, the workaround is to visit this URL:
https://builder.shoutem.com/forgot-password

And set yourself a password.

The e-mail used in the `shoutem login` is the email of your social account (in this case Google). That's also the e-mail the password reset will be sent to.

**Comment by franciscocpg** [comment]
Ok thanks. 

Maybe this workaround could be added to the docs for now?
