### ISSUE TITLE
New Version - clean clone configure failure

### ISSUE THREAD

**Issue by tripleorange** [shoutem/cli#36]
App breaks during shoutem configure after shoutem clone following platform update.

Shoutem Clone yields:

added 1041 packages in 30.663s
Creating extensions.js
Running preBuild for all extensions
[running preBuild] - shoutem.application: 1.211ms
Configuring Facebook login settings for iOS
{ Error: ENOENT: no such file or directory, open 'ios/Info.plist'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.writeFileSync (fs.js:1347:33)
    at configureFacebookSettingsIOS (/Users/tripleorange/dev/msc/Million-Shots-Club/extensions/shoute
m.auth/app/build.js:24:6)
    at preBuild (/Users/tripleorange/dev/msc/Million-Shots-Club/extensions/shoutem.auth/app/build.js:
53:3)

    at _.forEach.e (/Users/tripleorange/dev/msc/Million-Shots-Club/scripts/classes/app-configurator.j
s:144:13)
    at arrayEach (/Users/tripleorange/dev/msc/Million-Shots-Club/scripts/node_modules/lodash/lodash.j
s:537:11)
    at Function.forEach (/Users/tripleorange/dev/msc/Million-Shots-Club/scripts/node_modules/lodash/l
odash.js:9359:14)
    at AppConfigurator.executeBuildLifecycleHook (/Users/tripleorange/dev/msc/Million-Shots-Club/scri
pts/classes/app-configurator.js:134:7)
    at installer.installExtensions.then (/Users/tripleorange/dev/msc/Million-Shots-Club/scripts/class
es/app-configurator.js:113:31)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'ios/Info.plist' }

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @shoutem/platform@1.5.0 configure: `node scripts/configure`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @shoutem/platform@1.5.0 configure script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tripleorange/.npm/_logs/2017-12-10T21_21_17_065Z-debug.log
`npm run configure` failed with code 1

Shoutem configure yields:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'configure' ]
2 info using npm@5.3.0
3 info using node@v6.11.2
4 verbose run-script [ 'preconfigure', 'configure', 'postconfigure' ]
5 info lifecycle @shoutem/platform@1.5.0~preconfigure: @shoutem/platform@1.5.0
6 info lifecycle @shoutem/platform@1.5.0~configure: @shoutem/platform@1.5.0
7 verbose lifecycle @shoutem/platform@1.5.0~configure: unsafe-perm in lifecycle true
8 verbose lifecycle @shoutem/platform@1.5.0~configure: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/tripleorange/dev/millionshots/Million-Shots-Club/node_modules/.bin:/Applications/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/anaconda3/bin
9 verbose lifecycle @shoutem/platform@1.5.0~configure: CWD: /Users/tripleorange/dev/millionshots/Million-Shots-Club
10 silly lifecycle @shoutem/platform@1.5.0~configure: Args: [ '-c', 'node scripts/configure' ]
11 silly lifecycle @shoutem/platform@1.5.0~configure: Returned: code: 1  signal: null
12 info lifecycle @shoutem/platform@1.5.0~configure: Failed to exec configure script
13 verbose stack Error: @shoutem/platform@1.5.0 configure: `node scripts/configure`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid @shoutem/platform@1.5.0
15 verbose cwd /Users/tripleorange/dev/millionshots/Million-Shots-Club
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "configure"
18 verbose node v6.11.2
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error @shoutem/platform@1.5.0 configure: `node scripts/configure`
22 error Exit status 1
23 error Failed at the @shoutem/platform@1.5.0 configure script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Vladimir-Vdovic** [comment]
This was an issue regarding Facebook authentication. The issue has since been resolved.
