### ISSUE TITLE
Got the following error when installing @shoutem/cli globally

### ISSUE THREAD

**Issue by vincentwongso** [shoutem/cli#41]
/Users/xxxx/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Options {"loose":true} passed to /Users/xxxx/.config/yarn/global/node_modules/babel-preset-env/lib/index.js which does not accept options.

**Comment by banovotz** [comment]
__________________________________
Please type your reply at the top of the email...

------------------------------------------------------


Shoutem | Jan 09, 2018 05:12AM UTC   

Hello shoutem/cli,
thank you for submitting your request. We have received your request and are working on responding to you as soon as possible. If you have any additional information to add to this case, please reply to this email.


Thanks in advance for your patience and support.


------------------------------------------------------

For your reference this is Case #: 188298

------------------------------------------------------


Support powered by Assistly (http://www.assistly.com/)

[[956392bbec816e6c330aaec0daa96c8b19533456-1118912622]]

**Comment by vincentwongso** [comment]
OS: MacOS
Yarn: 1.3.2
NPM: 5.5.1

Actually the shoutem library get installed. But when I run:
`shoutem -v`
it throws the error above.

**Comment by Vladimir-Vdovic** [comment]
I've managed to reproduce this. 

It seems that his only happens when it's installed using yarn. For now, installing it with npm works without issue, so you can consider that a solution/work-around. 

`npm i -g @shoutem/cli`

We'll look into what the issue is specifically with the yarn install and if we can resolve it from our end.
