### ISSUE TITLE
apk location

### ISSUE THREAD

**Issue by ashokkumar88** [shoutem/cli#43]
Hi Team,

I run the command `shoutem configure --release`. It is showing BUILD SUCCESSFUL. But i did not find any apk file. There is no app/build/outputs folder created.

**Comment by Vladimir-Vdovic** [comment]
The `shoutem configure` command applies the configuration provided by the Builder, installs all dependencies of the project and links them to the project. It does not provide you with a build (.apk file). To generate the apk file do:
```
cd android && ./gradlew assembleRelease
```
From the root app directory.
