### ISSUE TITLE
shoutem last-error

### ISSUE THREAD

**Issue by ridz7** [shoutem/cli#5]
Hello

I download shoutem in local, i try to start it but i have this issue
Please can you help me ?
Thanks

{
  "name": "ChildProcessError",
  "code": 1,
  "childProcess": {
    "domain": null,
    "_events": {},
    "_eventsCount": 2,
    "_closesNeeded": 3,
    "_closesGot": 3,
    "connected": false,
    "signalCode": null,
    "exitCode": 1,
    "killed": false,
    "spawnfile": "C:\\WINDOWS\\system32\\cmd.exe",
    "_handle": null,
    "spawnargs": [
      "C:\\WINDOWS\\system32\\cmd.exe",
      "/d",
      "/s",
      "/c",
      "\"C:\\WINDOWS\\system32\\cmd.exe /s /c \"npm \"run\" \"configure\"\"\""
    ],
    "pid": 11392,
    "stdin": null,
    "stdout": {
      "connecting": false,
      "_hadError": false,
      "_handle": null,
      "_parent": null,
      "_host": null,
      "_readableState": {
        "objectMode": false,
        "highWaterMark": 16384,
        "buffer": {
          "head": null,
          "tail": null,
          "length": 0
        },
        "length": 0,
        "pipes": null,
        "pipesCount": 0,
        "flowing": false,
        "ended": true,
        "endEmitted": true,
        "reading": false,
        "sync": false,
        "needReadable": false,
        "emittedReadable": false,
        "readableListening": false,
        "resumeScheduled": false,
        "defaultEncoding": "utf8",
        "ranOut": false,
        "awaitDrain": 0,
        "readingMore": false,
        "decoder": null,
        "encoding": null
      },
      "readable": false,
      "domain": null,
      "_events": {},
      "_eventsCount": 4,
      "_writableState": {
        "objectMode": false,
        "highWaterMark": 16384,
        "needDrain": false,
        "ending": true,
        "ended": true,
        "finished": true,
        "decodeStrings": false,
        "defaultEncoding": "utf8",
        "length": 0,
        "writing": false,
        "corked": 0,
        "sync": true,
        "bufferProcessing": false,
        "writecb": null,
        "writelen": 0,
        "bufferedRequest": null,
        "lastBufferedRequest": null,
        "pendingcb": 0,
        "prefinished": true,
        "errorEmitted": false,
        "bufferedRequestCount": 0,
        "corkedRequestsFree": {
          "next": null,
          "entry": null
        }
      },
      "writable": false,
      "allowHalfOpen": false,
      "destroyed": true,
      "_bytesDispatched": 0,
      "_sockname": null,
      "_writev": null,
      "_pendingData": null,
      "_pendingEncoding": "",
      "server": null,
      "_server": null,
      "_consuming": true,
      "_idleNext": null,
      "_idlePrev": null,
      "_idleTimeout": -1
    },
    "stderr": {
      "connecting": false,
      "_hadError": false,
      "_handle": null,
      "_parent": null,
      "_host": null,
      "_readableState": {
        "objectMode": false,
        "highWaterMark": 16384,
        "buffer": {
          "head": null,
          "tail": null,
          "length": 0
        },
        "length": 0,
        "pipes": null,
        "pipesCount": 0,
        "flowing": false,
        "ended": true,
        "endEmitted": true,
        "reading": false,
        "sync": false,
        "needReadable": false,
        "emittedReadable": false,
        "readableListening": false,
        "resumeScheduled": false,
        "defaultEncoding": "utf8",
        "ranOut": false,
        "awaitDrain": 0,
        "readingMore": false,
        "decoder": null,
        "encoding": null
      },
      "readable": false,
      "domain": null,
      "_events": {},
      "_eventsCount": 4,
      "_writableState": {
        "objectMode": false,
        "highWaterMark": 16384,
        "needDrain": false,
        "ending": true,
        "ended": true,
        "finished": true,
        "decodeStrings": false,
        "defaultEncoding": "utf8",
        "length": 0,
        "writing": false,
        "corked": 0,
        "sync": true,
        "bufferProcessing": false,
        "writecb": null,
        "writelen": 0,
        "bufferedRequest": null,
        "lastBufferedRequest": null,
        "pendingcb": 0,
        "prefinished": true,
        "errorEmitted": false,
        "bufferedRequestCount": 0,
        "corkedRequestsFree": {
          "next": null,
          "entry": null
        }
      },
      "writable": false,
      "allowHalfOpen": false,
      "destroyed": true,
      "_bytesDispatched": 0,
      "_sockname": null,
      "_writev": null,
      "_pendingData": null,
      "_pendingEncoding": "",
      "server": null,
      "_server": null,
      "_consuming": true,
      "_idleNext": null,
      "_idlePrev": null,
      "_idleTimeout": -1
    },
    "stdio": [
      null,
      {
        "connecting": false,
        "_hadError": false,
        "_handle": null,
        "_parent": null,
        "_host": null,
        "_readableState": {
          "objectMode": false,
          "highWaterMark": 16384,
          "buffer": {
            "head": null,
            "tail": null,
            "length": 0
          },
          "length": 0,
          "pipes": null,
          "pipesCount": 0,
          "flowing": false,
          "ended": true,
          "endEmitted": true,
          "reading": false,
          "sync": false,
          "needReadable": false,
          "emittedReadable": false,
          "readableListening": false,
          "resumeScheduled": false,
          "defaultEncoding": "utf8",
          "ranOut": false,
          "awaitDrain": 0,
          "readingMore": false,
          "decoder": null,
          "encoding": null
        },
        "readable": false,
        "domain": null,
        "_events": {},
        "_eventsCount": 4,
        "_writableState": {
          "objectMode": false,
          "highWaterMark": 16384,
          "needDrain": false,
          "ending": true,
          "ended": true,
          "finished": true,
          "decodeStrings": false,
          "defaultEncoding": "utf8",
          "length": 0,
          "writing": false,
          "corked": 0,
          "sync": true,
          "bufferProcessing": false,
          "writecb": null,
          "writelen": 0,
          "bufferedRequest": null,
          "lastBufferedRequest": null,
          "pendingcb": 0,
          "prefinished": true,
          "errorEmitted": false,
          "bufferedRequestCount": 0,
          "corkedRequestsFree": {
            "next": null,
            "entry": null
          }
        },
        "writable": false,
        "allowHalfOpen": false,
        "destroyed": true,
        "_bytesDispatched": 0,
        "_sockname": null,
        "_writev": null,
        "_pendingData": null,
        "_pendingEncoding": "",
        "server": null,
        "_server": null,
        "_consuming": true,
        "_idleNext": null,
        "_idlePrev": null,
        "_idleTimeout": -1
      },
      {
        "connecting": false,
        "_hadError": false,
        "_handle": null,
        "_parent": null,
        "_host": null,
        "_readableState": {
          "objectMode": false,
          "highWaterMark": 16384,
          "buffer": {
            "head": null,
            "tail": null,
            "length": 0
          },
          "length": 0,
          "pipes": null,
          "pipesCount": 0,
          "flowing": false,
          "ended": true,
          "endEmitted": true,
          "reading": false,
          "sync": false,
          "needReadable": false,
          "emittedReadable": false,
          "readableListening": false,
          "resumeScheduled": false,
          "defaultEncoding": "utf8",
          "ranOut": false,
          "awaitDrain": 0,
          "readingMore": false,
          "decoder": null,
          "encoding": null
        },
        "readable": false,
        "domain": null,
        "_events": {},
        "_eventsCount": 4,
        "_writableState": {
          "objectMode": false,
          "highWaterMark": 16384,
          "needDrain": false,
          "ending": true,
          "ended": true,
          "finished": true,
          "decodeStrings": false,
          "defaultEncoding": "utf8",
          "length": 0,
          "writing": false,
          "corked": 0,
          "sync": true,
          "bufferProcessing": false,
          "writecb": null,
          "writelen": 0,
          "bufferedRequest": null,
          "lastBufferedRequest": null,
          "pendingcb": 0,
          "prefinished": true,
          "errorEmitted": false,
          "bufferedRequestCount": 0,
          "corkedRequestsFree": {
            "next": null,
            "entry": null
          }
        },
        "writable": false,
        "allowHalfOpen": false,
        "destroyed": true,
        "_bytesDispatched": 0,
        "_sockname": null,
        "_writev": null,
        "_pendingData": null,
        "_pendingEncoding": "",
        "server": null,
        "_server": null,
        "_consuming": true,
        "_idleNext": null,
        "_idlePrev": null,
        "_idleTimeout": -1
      }
    ]
  },
  "stdout": "\n> @shoutem/mobile-app@0.56.0 configure C:\\Users\\Rdz\\.shoutem\\production\\client\\6540\n> node scripts/configure\n\nstarting build for app 6540\ncleaning temp files: 9.292ms\ndownload configuration: 769.848ms\nLoad local extensions: 0.081ms\nInstalling dependencies:\n{\n  \"@shoutem/animation\": \"^0.10.2\",\n  \"@shoutem/core\": \"0.0.48\",\n  \"@shoutem/redux-composers\": \"0.1.0-beta.4\",\n  \"@shoutem/redux-io\": \"1.0.4\",\n  \"@shoutem/theme\": \"^0.9.0\",\n  \"@shoutem/ui\": \"0.11.1-support.3\",\n  \"@shoutem/ui-addons\": \"0.0.13\",\n  \"lodash\": \"^4.10.1\",\n  \"moment\": \"^2.13.0\",\n  \"whatwg-fetch\": \"1.0.0\",\n  \"react\": \"15.4.0\",\n  \"react-native\": \"0.39.2\",\n  \"react-native-browser-polyfill\": \"^0.1.1\",\n  \"react-native-calendar-manager\": \"git+https://git@bitbucket.org/fiveminutes/react-native-calendar-manager.git\",\n  \"react-native-code-push\": \"^1.16.1-beta\",\n  \"react-native-fbsdk\": \"0.4.0\",\n  \"react-native-google-analytics-bridge\": \"4.0.3\",\n  \"react-native-restart\": \"0.0.1\",\n  \"react-native-share\": \"1.0.13\",\n  \"react-native-vector-icons\": \"^2.0.3\",\n  \"react-native-maps\": \"git+https://github.com/5minutes/react-native-maps.git#google-play-dependency-fix\",\n  \"react-native-video\": \"^0.8.0\",\n  \"react-redux\": \"^5.0.2\",\n  \"redux\": \"^3.3.1\",\n  \"redux-action-buffer\": \"^1.0.1\",\n  \"redux-persist\": \"4.1.0\",\n  \"redux-api-middleware\": \"2.0.0-beta.1\",\n  \"redux-logger\": \"2.6.1\",\n  \"redux-thunk\": \"^2.0.0\",\n  \"shoutem.about\": \"https://extensions.static.shoutem.com/shoutem/about/0.9.8/app.tgz?timestamp=1491464876144\",\n  \"shoutem.analytics\": \"https://extensions.static.shoutem.com/shoutem/analytics/0.1.9/app.tgz?timestamp=1488546454968\",\n  \"shoutem.application\": \"https://extensions.static.shoutem.com/shoutem/application/0.2.11/app.tgz?timestamp=1491134153289\",\n  \"shoutem.arno-theme\": \"https://extensions.static.shoutem.com/shoutem/arno-theme/0.0.52/app.tgz?timestamp=1491464891213\",\n  \"shoutem.auth\": \"https://extensions.static.shoutem.com/shoutem/auth/0.6.4/app.tgz?timestamp=1491246106362\",\n  \"shoutem.books\": \"https://extensions.static.shoutem.com/shoutem/books/0.2.15/app.tgz?timestamp=1488546486187\",\n  \"shoutem.cms\": \"https://extensions.static.shoutem.com/shoutem/cms/0.10.12/app.tgz?timestamp=1491134263898\",\n  \"shoutem.events\": \"https://extensions.static.shoutem.com/shoutem/events/0.9.15/app.tgz?timestamp=1491464920296\",\n  \"shoutem.favorites\": \"https://extensions.static.shoutem.com/shoutem/favorites/0.1.9/app.tgz?timestamp=1488546514662\",\n  \"shoutem.google-analytics\": \"https://extensions.static.shoutem.com/shoutem/google-analytics/0.1.10/app.tgz?timestamp=1488546536359\",\n  \"shoutem.layouts\": \"https://extensions.static.shoutem.com/shoutem/layouts/0.1.16/app.tgz?timestamp=1491294133439\",\n  \"shoutem.menu\": \"https://extensions.static.shoutem.com/shoutem/menu/0.10.12/app.tgz?timestamp=1488546554846\",\n  \"shoutem.navigation\": \"https://extensions.static.shoutem.com/shoutem/navigation/0.5.29/app.tgz?timestamp=1491134356159\",\n  \"shoutem.news\": \"https://extensions.static.shoutem.com/shoutem/news/0.9.16/app.tgz?timestamp=1491251998512\",\n  \"shoutem.people\": \"https://extensions.static.shoutem.com/shoutem/people/0.10.14/app.tgz?timestamp=1490114177545\",\n  \"shoutem.persist\": \"https://extensions.static.shoutem.com/shoutem/persist/0.1.8/app.tgz?timestamp=1488546585427\",\n  \"shoutem.photos\": \"https://extensions.static.shoutem.com/shoutem/photos/0.9.6/app.tgz?timestamp=1491134419096\",\n  \"shoutem.places\": \"https://extensions.static.shoutem.com/shoutem/places/0.9.17/app.tgz?timestamp=1491464975377\",\n  \"shoutem.platform-analytics\": \"https://extensions.static.shoutem.com/shoutem/platform-analytics/0.1.9/app.tgz?timestamp=1488546597902\",\n  \"shoutem.preview\": \"https://extensions.static.shoutem.com/shoutem/preview/0.1.8/app.tgz?timestamp=1488546601636\",\n  \"shoutem.products\": \"https://extensions.static.shoutem.com/shoutem/products/0.9.16/app.tgz?timestamp=1488546606139\",\n  \"shoutem.push-notifications\": \"https://extensions.static.shoutem.com/shoutem/push-notifications/0.1.12/app.tgz?timestamp=1490114200900\",\n  \"shoutem.rss\": \"https://extensions.static.shoutem.com/shoutem/rss/0.2.13/app.tgz?timestamp=1490114214416\",\n  \"shoutem.rss-news\": \"https://extensions.static.shoutem.com/shoutem/rss-news/0.9.14/app.tgz?timestamp=1490114219595\",\n  \"shoutem.rss-photos\": \"https://extensions.static.shoutem.com/shoutem/rss-photos/0.9.6/app.tgz?timestamp=1491134467416\",\n  \"shoutem.rss-videos\": \"https://extensions.static.shoutem.com/shoutem/rss-videos/0.10.11/app.tgz?timestamp=1488546638820\",\n  \"shoutem.rubicon-noir-theme\": \"https://extensions.static.shoutem.com/shoutem/rubicon-noir-theme/0.0.17/app.tgz?timestamp=1491246214506\",\n  \"shoutem.rubicon-rose-theme\": \"https://extensions.static.shoutem.com/shoutem/rubicon-rose-theme/0.0.17/app.tgz?timestamp=1491246220261\",\n  \"shoutem.rubicon-theme\": \"https://extensions.static.shoutem.com/shoutem/rubicon-theme/0.1.50/app.tgz?timestamp=1491465044533\",\n  \"shoutem.shopify\": \"https://extensions.static.shoutem.com/shoutem/shopify/0.1.9/app.tgz?timestamp=1490974747036\",\n  \"shoutem.sub-navigation\": \"https://extensions.static.shoutem.com/shoutem/sub-navigation/0.1.1/app.tgz?timestamp=1488546693122\",\n  \"shoutem.theme\": \"https://extensions.static.shoutem.com/shoutem/theme/0.1.7/app.tgz?timestamp=1487859791935\",\n  \"shoutem.video\": \"https://extensions.static.shoutem.com/shoutem/video/0.10.12/app.tgz?timestamp=1488546697219\",\n  \"shoutem.web-view\": \"https://extensions.static.shoutem.com/shoutem/web-view/0.9.6/app.tgz?timestamp=1490974764904\"\n}\n\u001b[2K\u001b[1G\u001b[1myarn install v0.23.4\u001b[22m\n\u001b[2K\u001b[1G\u001b[94minfo\u001b[39m No lockfile found.\n\u001b[2K\u001b[1G\u001b[2m[1/4]\u001b[22m Resolving packages...\n\u001b[2K\u001b[1G\u001b[94minfo\u001b[39m Visit \u001b[1mhttps://yarnpkg.com/en/docs/cli/install\u001b[22m for documentation about this command.\n{ Error: cmd: Command failed with exit code 1\n    at ChildProcess.whenDone (C:\\Users\\Rdz\\.shoutem\\production\\client\\6540\\scripts\\node_modules\\superspawn\\lib\\index.js:172:23)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:194:7)\n    at maybeClose (internal/child_process.js:899:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) code: 1 }\n",
  "stderr": "\u001b[2K\u001b[1G\u001b[31merror\u001b[39m Refusing to download the git repo {\"protocol\":\"https:\",\"hostname\":\"bitbucket.org\",\"repository\":\"https://git@bitbucket.org/fiveminutes/react-native-calendar-manager.git\"} over HTTPS without a commit hash - possible certificate error?\n\nnpm ERR! Windows_NT 10.0.14393\nnpm ERR! argv \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\bin\\\\npm-cli.js\" \"run\" \"configure\"\nnpm ERR! node v7.10.0\nnpm ERR! npm  v4.2.0\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! @shoutem/mobile-app@0.56.0 configure: `node scripts/configure`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @shoutem/mobile-app@0.56.0 configure script 'node scripts/configure'.\nnpm ERR! Make sure you have the latest version of node.js and npm installed.\nnpm ERR! If you do, this is most likely a problem with the @shoutem/mobile-app package,\nnpm ERR! not with npm itself.\nnpm ERR! Tell the author that this fails on your system:\nnpm ERR!     node scripts/configure\nnpm ERR! You can get information on how to open an issue for this project with:\nnpm ERR!     npm bugs @shoutem/mobile-app\nnpm ERR! Or if that isn't available, you can get their info via:\nnpm ERR!     npm owner ls @shoutem/mobile-app\nnpm ERR! There is likely additional logging output above.\nnpm WARN Local package.json exists, but node_modules missing, did you mean to install?\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     C:\\Users\\Rdz\\AppData\\Roaming\\npm-cache\\_logs\\2017-05-05T13_44_03_888Z-debug.log\n",
  "stack": "Error: `npm run configure` failed with code 1\n    at ChildProcess.<anonymous> (C:\\Users\\Rdz\\AppData\\Roaming\\npm\\node_modules\\@shoutem\\cli\\node_modules\\child-process-promise\\lib\\index.js:132:23)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:194:7)\n    at ChildProcess.cp.emit (C:\\Users\\Rdz\\AppData\\Roaming\\npm\\node_modules\\@shoutem\\cli\\node_modules\\cross-spawn\\lib\\enoent.js:40:29)\n    at maybeClose (internal/child_process.js:899:16)\n    at Socket.<anonymous> (internal/child_process.js:342:11)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:191:7)\n    at Pipe._handle.close [as _onclose] (net.js:511:12)",
  "message": "`npm run configure` failed with code 1"
}

**Comment by vivakimkwa** [comment]
I am experiencing the same issue

**Comment by Vladimir-Vdovic** [comment]
Can you guys elaborate on what exactly you mean by "downloaded the app in local"? Did you use `shoutem pull-app` or am I misunderstanding the issue?
